[pytest]
addopts = --json-report --json-report-file=test_dashboard/report.json --cov=Super_Market --cov-report=json:test_dashboard/coverage.json --ignore=test_dashboard --ignore=tests/ui --ignore=app.py --ignore=Super_Market --ignore=test_output.txt -p no:warnings
markers =
    e2e: End-to-end tests

[pytest-watch]
ignore = test_dashboard
